apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend2
  labels:
    app: backend2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend2
                port:
                  number: 3000


